/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type Message = {
  __typename: "Message",
  content?: string | null,
  conversationId?: string | null,
  createdAt: string,
  id: string,
  isRead?: boolean | null,
  recipient?: UserProfile | null,
  recipientId?: string | null,
  sender?: UserProfile | null,
  senderId?: string | null,
  subject?: string | null,
  updatedAt: string,
};

export type UserProfile = {
  __typename: "UserProfile",
  accountStatus?: UserProfileAccountStatus | null,
  bio?: string | null,
  contributionGoals?: string | null,
  createdAt: string,
  deletedAt?: string | null,
  email?: string | null,
  experience?: string | null,
  expertSupportNeeded?: string | null,
  githubUrl?: string | null,
  id: string,
  instagramUrl?: string | null,
  isDeleted?: boolean | null,
  isProfileHidden?: boolean | null,
  latitude?: number | null,
  linkedinUrl?: string | null,
  location?: string | null,
  longitude?: number | null,
  messagingEnabled?: boolean | null,
  missionValuesAlignment?: string | null,
  owner?: string | null,
  passions?: string | null,
  portfolioUrl?: string | null,
  preferredEngagement?: string | null,
  projectDetails?: string | null,
  receivedMessages?: ModelMessageConnection | null,
  sentMessages?: ModelMessageConnection | null,
  skills?: string | null,
  statusMessage?: string | null,
  timeCommitment?: string | null,
  timezone?: string | null,
  twitterUrl?: string | null,
  updatedAt: string,
  userType?: UserProfileUserType | null,
  username?: string | null,
  values?: string | null,
  ventureInterests?: string | null,
  websiteUrl?: string | null,
};

export enum UserProfileAccountStatus {
  active = "active",
  busy = "busy",
  inactive = "inactive",
}


export type ModelMessageConnection = {
  __typename: "ModelMessageConnection",
  items:  Array<Message | null >,
  nextToken?: string | null,
};

export enum UserProfileUserType {
  both = "both",
  expert = "expert",
  ventures = "ventures",
}


export type Todo = {
  __typename: "Todo",
  content?: string | null,
  createdAt: string,
  id: string,
  updatedAt: string,
};

export type ModelMessageFilterInput = {
  and?: Array< ModelMessageFilterInput | null > | null,
  content?: ModelStringInput | null,
  conversationId?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  id?: ModelIDInput | null,
  isRead?: ModelBooleanInput | null,
  not?: ModelMessageFilterInput | null,
  or?: Array< ModelMessageFilterInput | null > | null,
  recipientId?: ModelStringInput | null,
  senderId?: ModelStringInput | null,
  subject?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelStringInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  _null = "_null",
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
}


export type ModelSizeInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export type ModelIDInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  size?: ModelSizeInput | null,
};

export type ModelBooleanInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  eq?: boolean | null,
  ne?: boolean | null,
};

export type ModelTodoFilterInput = {
  and?: Array< ModelTodoFilterInput | null > | null,
  content?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  id?: ModelIDInput | null,
  not?: ModelTodoFilterInput | null,
  or?: Array< ModelTodoFilterInput | null > | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelTodoConnection = {
  __typename: "ModelTodoConnection",
  items:  Array<Todo | null >,
  nextToken?: string | null,
};

export type ModelUserProfileFilterInput = {
  accountStatus?: ModelUserProfileAccountStatusInput | null,
  and?: Array< ModelUserProfileFilterInput | null > | null,
  bio?: ModelStringInput | null,
  contributionGoals?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  deletedAt?: ModelStringInput | null,
  email?: ModelStringInput | null,
  experience?: ModelStringInput | null,
  expertSupportNeeded?: ModelStringInput | null,
  githubUrl?: ModelStringInput | null,
  id?: ModelIDInput | null,
  instagramUrl?: ModelStringInput | null,
  isDeleted?: ModelBooleanInput | null,
  isProfileHidden?: ModelBooleanInput | null,
  latitude?: ModelFloatInput | null,
  linkedinUrl?: ModelStringInput | null,
  location?: ModelStringInput | null,
  longitude?: ModelFloatInput | null,
  messagingEnabled?: ModelBooleanInput | null,
  missionValuesAlignment?: ModelStringInput | null,
  not?: ModelUserProfileFilterInput | null,
  or?: Array< ModelUserProfileFilterInput | null > | null,
  owner?: ModelStringInput | null,
  passions?: ModelStringInput | null,
  portfolioUrl?: ModelStringInput | null,
  preferredEngagement?: ModelStringInput | null,
  projectDetails?: ModelStringInput | null,
  skills?: ModelStringInput | null,
  statusMessage?: ModelStringInput | null,
  timeCommitment?: ModelStringInput | null,
  timezone?: ModelStringInput | null,
  twitterUrl?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  userType?: ModelUserProfileUserTypeInput | null,
  username?: ModelStringInput | null,
  values?: ModelStringInput | null,
  ventureInterests?: ModelStringInput | null,
  websiteUrl?: ModelStringInput | null,
};

export type ModelUserProfileAccountStatusInput = {
  eq?: UserProfileAccountStatus | null,
  ne?: UserProfileAccountStatus | null,
};

export type ModelFloatInput = {
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
};

export type ModelUserProfileUserTypeInput = {
  eq?: UserProfileUserType | null,
  ne?: UserProfileUserType | null,
};

export type ModelUserProfileConnection = {
  __typename: "ModelUserProfileConnection",
  items:  Array<UserProfile | null >,
  nextToken?: string | null,
};

export type ModelMessageConditionInput = {
  and?: Array< ModelMessageConditionInput | null > | null,
  content?: ModelStringInput | null,
  conversationId?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  isRead?: ModelBooleanInput | null,
  not?: ModelMessageConditionInput | null,
  or?: Array< ModelMessageConditionInput | null > | null,
  recipientId?: ModelStringInput | null,
  senderId?: ModelStringInput | null,
  subject?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type CreateMessageInput = {
  content?: string | null,
  conversationId?: string | null,
  id?: string | null,
  isRead?: boolean | null,
  recipientId?: string | null,
  senderId?: string | null,
  subject?: string | null,
};

export type ModelTodoConditionInput = {
  and?: Array< ModelTodoConditionInput | null > | null,
  content?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  not?: ModelTodoConditionInput | null,
  or?: Array< ModelTodoConditionInput | null > | null,
  updatedAt?: ModelStringInput | null,
};

export type CreateTodoInput = {
  content?: string | null,
  id?: string | null,
};

export type ModelUserProfileConditionInput = {
  accountStatus?: ModelUserProfileAccountStatusInput | null,
  and?: Array< ModelUserProfileConditionInput | null > | null,
  bio?: ModelStringInput | null,
  contributionGoals?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  deletedAt?: ModelStringInput | null,
  email?: ModelStringInput | null,
  experience?: ModelStringInput | null,
  expertSupportNeeded?: ModelStringInput | null,
  githubUrl?: ModelStringInput | null,
  instagramUrl?: ModelStringInput | null,
  isDeleted?: ModelBooleanInput | null,
  isProfileHidden?: ModelBooleanInput | null,
  latitude?: ModelFloatInput | null,
  linkedinUrl?: ModelStringInput | null,
  location?: ModelStringInput | null,
  longitude?: ModelFloatInput | null,
  messagingEnabled?: ModelBooleanInput | null,
  missionValuesAlignment?: ModelStringInput | null,
  not?: ModelUserProfileConditionInput | null,
  or?: Array< ModelUserProfileConditionInput | null > | null,
  owner?: ModelStringInput | null,
  passions?: ModelStringInput | null,
  portfolioUrl?: ModelStringInput | null,
  preferredEngagement?: ModelStringInput | null,
  projectDetails?: ModelStringInput | null,
  skills?: ModelStringInput | null,
  statusMessage?: ModelStringInput | null,
  timeCommitment?: ModelStringInput | null,
  timezone?: ModelStringInput | null,
  twitterUrl?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  userType?: ModelUserProfileUserTypeInput | null,
  username?: ModelStringInput | null,
  values?: ModelStringInput | null,
  ventureInterests?: ModelStringInput | null,
  websiteUrl?: ModelStringInput | null,
};

export type CreateUserProfileInput = {
  accountStatus?: UserProfileAccountStatus | null,
  bio?: string | null,
  contributionGoals?: string | null,
  deletedAt?: string | null,
  email?: string | null,
  experience?: string | null,
  expertSupportNeeded?: string | null,
  githubUrl?: string | null,
  id?: string | null,
  instagramUrl?: string | null,
  isDeleted?: boolean | null,
  isProfileHidden?: boolean | null,
  latitude?: number | null,
  linkedinUrl?: string | null,
  location?: string | null,
  longitude?: number | null,
  messagingEnabled?: boolean | null,
  missionValuesAlignment?: string | null,
  passions?: string | null,
  portfolioUrl?: string | null,
  preferredEngagement?: string | null,
  projectDetails?: string | null,
  skills?: string | null,
  statusMessage?: string | null,
  timeCommitment?: string | null,
  timezone?: string | null,
  twitterUrl?: string | null,
  userType?: UserProfileUserType | null,
  username?: string | null,
  values?: string | null,
  ventureInterests?: string | null,
  websiteUrl?: string | null,
};

export type DeleteMessageInput = {
  id: string,
};

export type DeleteTodoInput = {
  id: string,
};

export type DeleteUserProfileInput = {
  id: string,
};

export type UpdateMessageInput = {
  content?: string | null,
  conversationId?: string | null,
  id: string,
  isRead?: boolean | null,
  recipientId?: string | null,
  senderId?: string | null,
  subject?: string | null,
};

export type UpdateTodoInput = {
  content?: string | null,
  id: string,
};

export type UpdateUserProfileInput = {
  accountStatus?: UserProfileAccountStatus | null,
  bio?: string | null,
  contributionGoals?: string | null,
  deletedAt?: string | null,
  email?: string | null,
  experience?: string | null,
  expertSupportNeeded?: string | null,
  githubUrl?: string | null,
  id: string,
  instagramUrl?: string | null,
  isDeleted?: boolean | null,
  isProfileHidden?: boolean | null,
  latitude?: number | null,
  linkedinUrl?: string | null,
  location?: string | null,
  longitude?: number | null,
  messagingEnabled?: boolean | null,
  missionValuesAlignment?: string | null,
  passions?: string | null,
  portfolioUrl?: string | null,
  preferredEngagement?: string | null,
  projectDetails?: string | null,
  skills?: string | null,
  statusMessage?: string | null,
  timeCommitment?: string | null,
  timezone?: string | null,
  twitterUrl?: string | null,
  userType?: UserProfileUserType | null,
  username?: string | null,
  values?: string | null,
  ventureInterests?: string | null,
  websiteUrl?: string | null,
};

export type ModelSubscriptionMessageFilterInput = {
  and?: Array< ModelSubscriptionMessageFilterInput | null > | null,
  content?: ModelSubscriptionStringInput | null,
  conversationId?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  isRead?: ModelSubscriptionBooleanInput | null,
  or?: Array< ModelSubscriptionMessageFilterInput | null > | null,
  recipientId?: ModelSubscriptionStringInput | null,
  senderId?: ModelSubscriptionStringInput | null,
  subject?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionStringInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  in?: Array< string | null > | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionIDInput = {
  beginsWith?: string | null,
  between?: Array< string | null > | null,
  contains?: string | null,
  eq?: string | null,
  ge?: string | null,
  gt?: string | null,
  in?: Array< string | null > | null,
  le?: string | null,
  lt?: string | null,
  ne?: string | null,
  notContains?: string | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  eq?: boolean | null,
  ne?: boolean | null,
};

export type ModelSubscriptionTodoFilterInput = {
  and?: Array< ModelSubscriptionTodoFilterInput | null > | null,
  content?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  or?: Array< ModelSubscriptionTodoFilterInput | null > | null,
  updatedAt?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionUserProfileFilterInput = {
  accountStatus?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionUserProfileFilterInput | null > | null,
  bio?: ModelSubscriptionStringInput | null,
  contributionGoals?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  deletedAt?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  experience?: ModelSubscriptionStringInput | null,
  expertSupportNeeded?: ModelSubscriptionStringInput | null,
  githubUrl?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  instagramUrl?: ModelSubscriptionStringInput | null,
  isDeleted?: ModelSubscriptionBooleanInput | null,
  isProfileHidden?: ModelSubscriptionBooleanInput | null,
  latitude?: ModelSubscriptionFloatInput | null,
  linkedinUrl?: ModelSubscriptionStringInput | null,
  location?: ModelSubscriptionStringInput | null,
  longitude?: ModelSubscriptionFloatInput | null,
  messagingEnabled?: ModelSubscriptionBooleanInput | null,
  missionValuesAlignment?: ModelSubscriptionStringInput | null,
  or?: Array< ModelSubscriptionUserProfileFilterInput | null > | null,
  owner?: ModelStringInput | null,
  passions?: ModelSubscriptionStringInput | null,
  portfolioUrl?: ModelSubscriptionStringInput | null,
  preferredEngagement?: ModelSubscriptionStringInput | null,
  projectDetails?: ModelSubscriptionStringInput | null,
  skills?: ModelSubscriptionStringInput | null,
  statusMessage?: ModelSubscriptionStringInput | null,
  timeCommitment?: ModelSubscriptionStringInput | null,
  timezone?: ModelSubscriptionStringInput | null,
  twitterUrl?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  userType?: ModelSubscriptionStringInput | null,
  username?: ModelSubscriptionStringInput | null,
  values?: ModelSubscriptionStringInput | null,
  ventureInterests?: ModelSubscriptionStringInput | null,
  websiteUrl?: ModelSubscriptionStringInput | null,
};

export type ModelSubscriptionFloatInput = {
  between?: Array< number | null > | null,
  eq?: number | null,
  ge?: number | null,
  gt?: number | null,
  in?: Array< number | null > | null,
  le?: number | null,
  lt?: number | null,
  ne?: number | null,
  notIn?: Array< number | null > | null,
};

export type GetMessageQueryVariables = {
  id: string,
};

export type GetMessageQuery = {
  getMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type GetTodoQueryVariables = {
  id: string,
};

export type GetTodoQuery = {
  getTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type GetUserProfileQueryVariables = {
  id: string,
};

export type GetUserProfileQuery = {
  getUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};

export type ListMessagesQueryVariables = {
  filter?: ModelMessageFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListMessagesQuery = {
  listMessages?:  {
    __typename: "ModelMessageConnection",
    items:  Array< {
      __typename: "Message",
      content?: string | null,
      conversationId?: string | null,
      createdAt: string,
      id: string,
      isRead?: boolean | null,
      recipientId?: string | null,
      senderId?: string | null,
      subject?: string | null,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListTodosQueryVariables = {
  filter?: ModelTodoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListTodosQuery = {
  listTodos?:  {
    __typename: "ModelTodoConnection",
    items:  Array< {
      __typename: "Todo",
      content?: string | null,
      createdAt: string,
      id: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListUserProfilesQueryVariables = {
  filter?: ModelUserProfileFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUserProfilesQuery = {
  listUserProfiles?:  {
    __typename: "ModelUserProfileConnection",
    items:  Array< {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type CreateMessageMutationVariables = {
  condition?: ModelMessageConditionInput | null,
  input: CreateMessageInput,
};

export type CreateMessageMutation = {
  createMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type CreateTodoMutationVariables = {
  condition?: ModelTodoConditionInput | null,
  input: CreateTodoInput,
};

export type CreateTodoMutation = {
  createTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type CreateUserProfileMutationVariables = {
  condition?: ModelUserProfileConditionInput | null,
  input: CreateUserProfileInput,
};

export type CreateUserProfileMutation = {
  createUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};

export type DeleteMessageMutationVariables = {
  condition?: ModelMessageConditionInput | null,
  input: DeleteMessageInput,
};

export type DeleteMessageMutation = {
  deleteMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type DeleteTodoMutationVariables = {
  condition?: ModelTodoConditionInput | null,
  input: DeleteTodoInput,
};

export type DeleteTodoMutation = {
  deleteTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type DeleteUserProfileMutationVariables = {
  condition?: ModelUserProfileConditionInput | null,
  input: DeleteUserProfileInput,
};

export type DeleteUserProfileMutation = {
  deleteUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};

export type UpdateMessageMutationVariables = {
  condition?: ModelMessageConditionInput | null,
  input: UpdateMessageInput,
};

export type UpdateMessageMutation = {
  updateMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type UpdateTodoMutationVariables = {
  condition?: ModelTodoConditionInput | null,
  input: UpdateTodoInput,
};

export type UpdateTodoMutation = {
  updateTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type UpdateUserProfileMutationVariables = {
  condition?: ModelUserProfileConditionInput | null,
  input: UpdateUserProfileInput,
};

export type UpdateUserProfileMutation = {
  updateUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};

export type OnCreateMessageSubscriptionVariables = {
  filter?: ModelSubscriptionMessageFilterInput | null,
};

export type OnCreateMessageSubscription = {
  onCreateMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type OnCreateTodoSubscriptionVariables = {
  filter?: ModelSubscriptionTodoFilterInput | null,
};

export type OnCreateTodoSubscription = {
  onCreateTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type OnCreateUserProfileSubscriptionVariables = {
  filter?: ModelSubscriptionUserProfileFilterInput | null,
  owner?: string | null,
};

export type OnCreateUserProfileSubscription = {
  onCreateUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};

export type OnDeleteMessageSubscriptionVariables = {
  filter?: ModelSubscriptionMessageFilterInput | null,
};

export type OnDeleteMessageSubscription = {
  onDeleteMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type OnDeleteTodoSubscriptionVariables = {
  filter?: ModelSubscriptionTodoFilterInput | null,
};

export type OnDeleteTodoSubscription = {
  onDeleteTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteUserProfileSubscriptionVariables = {
  filter?: ModelSubscriptionUserProfileFilterInput | null,
  owner?: string | null,
};

export type OnDeleteUserProfileSubscription = {
  onDeleteUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};

export type OnUpdateMessageSubscriptionVariables = {
  filter?: ModelSubscriptionMessageFilterInput | null,
};

export type OnUpdateMessageSubscription = {
  onUpdateMessage?:  {
    __typename: "Message",
    content?: string | null,
    conversationId?: string | null,
    createdAt: string,
    id: string,
    isRead?: boolean | null,
    recipient?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    recipientId?: string | null,
    sender?:  {
      __typename: "UserProfile",
      accountStatus?: UserProfileAccountStatus | null,
      bio?: string | null,
      contributionGoals?: string | null,
      createdAt: string,
      deletedAt?: string | null,
      email?: string | null,
      experience?: string | null,
      expertSupportNeeded?: string | null,
      githubUrl?: string | null,
      id: string,
      instagramUrl?: string | null,
      isDeleted?: boolean | null,
      isProfileHidden?: boolean | null,
      latitude?: number | null,
      linkedinUrl?: string | null,
      location?: string | null,
      longitude?: number | null,
      messagingEnabled?: boolean | null,
      missionValuesAlignment?: string | null,
      owner?: string | null,
      passions?: string | null,
      portfolioUrl?: string | null,
      preferredEngagement?: string | null,
      projectDetails?: string | null,
      skills?: string | null,
      statusMessage?: string | null,
      timeCommitment?: string | null,
      timezone?: string | null,
      twitterUrl?: string | null,
      updatedAt: string,
      userType?: UserProfileUserType | null,
      username?: string | null,
      values?: string | null,
      ventureInterests?: string | null,
      websiteUrl?: string | null,
    } | null,
    senderId?: string | null,
    subject?: string | null,
    updatedAt: string,
  } | null,
};

export type OnUpdateTodoSubscriptionVariables = {
  filter?: ModelSubscriptionTodoFilterInput | null,
};

export type OnUpdateTodoSubscription = {
  onUpdateTodo?:  {
    __typename: "Todo",
    content?: string | null,
    createdAt: string,
    id: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateUserProfileSubscriptionVariables = {
  filter?: ModelSubscriptionUserProfileFilterInput | null,
  owner?: string | null,
};

export type OnUpdateUserProfileSubscription = {
  onUpdateUserProfile?:  {
    __typename: "UserProfile",
    accountStatus?: UserProfileAccountStatus | null,
    bio?: string | null,
    contributionGoals?: string | null,
    createdAt: string,
    deletedAt?: string | null,
    email?: string | null,
    experience?: string | null,
    expertSupportNeeded?: string | null,
    githubUrl?: string | null,
    id: string,
    instagramUrl?: string | null,
    isDeleted?: boolean | null,
    isProfileHidden?: boolean | null,
    latitude?: number | null,
    linkedinUrl?: string | null,
    location?: string | null,
    longitude?: number | null,
    messagingEnabled?: boolean | null,
    missionValuesAlignment?: string | null,
    owner?: string | null,
    passions?: string | null,
    portfolioUrl?: string | null,
    preferredEngagement?: string | null,
    projectDetails?: string | null,
    receivedMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    sentMessages?:  {
      __typename: "ModelMessageConnection",
      nextToken?: string | null,
    } | null,
    skills?: string | null,
    statusMessage?: string | null,
    timeCommitment?: string | null,
    timezone?: string | null,
    twitterUrl?: string | null,
    updatedAt: string,
    userType?: UserProfileUserType | null,
    username?: string | null,
    values?: string | null,
    ventureInterests?: string | null,
    websiteUrl?: string | null,
  } | null,
};
